# Generated by Django 3.2.14 on 2023-01-06 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mail_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=mail_app.models.user_directory_path),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "Pdf"), ("csv", "Csv")],
                        default="pdf",
                        editable=False,
                        max_length=8,
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("cdr_user", "Cdr User"),
                            ("cdr_location", "Cdr Location"),
                            ("sepa", "Sepa"),
                            ("invoice", "Invoice"),
                            ("offer", "Offer"),
                        ],
                        default="invoice",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=mail_app.models.user_directory_path),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "Pdf"), ("csv", "Csv")],
                        default="csv",
                        editable=False,
                        max_length=8,
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("cdr_user", "Cdr User"),
                            ("cdr_location", "Cdr Location"),
                            ("sepa", "Sepa"),
                            ("invoice", "Invoice"),
                            ("offer", "Offer"),
                        ],
                        default="cdr_user",
                        max_length=32,
                    ),
                ),
                ("activated", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
