# Generated by Django 3.2.14 on 2023-01-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csv",
            name="red",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pdf",
            name="red",
            field=models.BooleanField(default=False),
        ),
    ]
