# Generated by Django 4.2.3 on 2023-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_auto_20230112_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdf',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
