# Generated by Django 3.2.14 on 2022-11-08 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ChargePointHandler", "0023_auto_20221108_1017"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_stage",
                    models.CharField(
                        choices=[
                            ("In Planung", "In Planung"),
                            ("In Bau", "In Bau"),
                            ("Neubau", "Neubau"),
                            ("Altbau", "Altbau"),
                        ],
                        default="Altbau",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("parking_spaces", models.IntegerField()),
                (
                    "particularities",
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                ("number_net_connections", models.IntegerField(blank=True, null=True)),
                ("requested_capacity", models.IntegerField(blank=True, null=True)),
                ("approved_capacity", models.IntegerField(blank=True, null=True)),
                ("spare_capacity", models.IntegerField(blank=True, null=True)),
                ("user_group", models.TextField(blank=True, null=True)),
                ("existing_charging_stations", models.BooleanField(default=False)),
                (
                    "installer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ChargePointHandler.location",
                    ),
                ),
                (
                    "property_manager",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(null=True)),
                ("position", models.CharField(max_length=256, null=True)),
                (
                    "installation_stage",
                    models.CharField(
                        choices=[
                            ("NO_INSTALLATION", "NO_INSTALLATION"),
                            ("CABLE", "CABLE"),
                            ("EVSE_DOCK", "EVSE_DOCK"),
                            ("EVSE", "EVSE"),
                        ],
                        default="NO_INSTALLATION",
                        max_length=128,
                    ),
                ),
                (
                    "parking_space_type",
                    models.CharField(
                        choices=[
                            ("UNDERGROUND_CAR_PARK", "UNDERGROUND_CAR_PARK"),
                            ("CAR_PARK", "CAR_PARK"),
                            ("OUTSIDE_PARKING_SPACE", "OUTSIDE_PARKING_SPACE"),
                            ("SINGLE_GARAGE", "SINGLE_GARAGE"),
                            ("DOUBLE_PARKING", "DOUBLE_PARKING"),
                        ],
                        default="UNDERGROUND_CAR_PARK",
                        max_length=128,
                    ),
                ),
                (
                    "charging_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ChargePointHandler.chargingstation",
                    ),
                ),
                (
                    "location_detail",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_management.locationdetail",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_created=True)),
                ("target_date", models.DateField()),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(max_length=1024)),
                (
                    "location_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_management.locationdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="media"),
                ),
                (
                    "location_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_management.locationdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstallationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charging_stations", models.IntegerField()),
                ("prepared_parking_spaces", models.IntegerField()),
                ("basic_installation", models.IntegerField()),
                (
                    "location_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_management.locationdetail",
                    ),
                ),
            ],
        ),
    ]
