# Generated by Django 3.2.14 on 2022-11-17 10:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationdetail",
            name="parking_space_types",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Tiefgarage", "Tiefgarage"),
                    ("Parkhaus", "Parkhaus"),
                    ("Parkfläche außen", "Parkfläche außen"),
                    ("Einzelgarage", "Einzelgarage"),
                    ("Carport", "Carport"),
                    ("Doppelparker", "Doppelparker"),
                ],
                max_length=70,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="parking_space_type",
            field=models.CharField(
                choices=[
                    ("Tiefgarage", "Tiefgarage"),
                    ("Parkhaus", "Parkhaus"),
                    ("Parkfläche außen", "Parkfläche außen"),
                    ("Einzelgarage", "Einzelgarage"),
                    ("Carport", "Carport"),
                    ("Doppelparker", "Doppelparker"),
                ],
                default="Tiefgarage",
                max_length=128,
            ),
        ),
    ]
