# Generated by Django 3.2.14 on 2023-05-08 13:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_auto_20221118_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='parking_space_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tiefgarage', 'Tiefgarage'), ('Parkhaus', 'Parkhaus'), ('Parkfläche außen', 'Parkfläche außen'), ('Einzelgarage', 'Einzelgarage'), ('Carport', 'Carport'), ('Doppelparker', 'Doppelparker')], max_length=30, null=True),
        ),
    ]
