# Generated by Django 4.2.16 on 2025-01-06 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0004_alter_locationdetail_parking_space_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_purchase_price", models.FloatField()),
                ("total_selling_price_margin", models.FloatField()),
                ("group_name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_purchase_price", models.FloatField()),
                ("total_selling_price_margin", models.FloatField()),
                ("execution_date", models.DateField(default=datetime.date(2025, 1, 6))),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("group_id", models.IntegerField()),
                (
                    "item_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_management.itemgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internal_description_de", models.TextField()),
                ("internal_description_en", models.TextField()),
                ("customer_description_de", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_margin", models.FloatField(default=30.0, help_text="in %")),
                ("taxes", models.FloatField(default=19.0, help_text="in %")),
                ("purchase_price", models.FloatField(default=0)),
                ("selling_price_inflation", models.FloatField(default=0)),
                ("selling_price_safety_margin", models.FloatField(default=0)),
                ("source", models.CharField(max_length=512, null=True)),
                ("status", models.CharField(max_length=128)),
                (
                    "product_group",
                    models.ManyToManyField(to="project_management.productgroup"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemgroup",
            name="project_calculation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.projectcalculation",
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_purchase_price", models.FloatField()),
                ("total_selling_price_margin", models.FloatField()),
                ("quantity_netto", models.FloatField(default=0)),
                ("quantity_brutto", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_management.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
