# Generated by Django 4.2.16 on 2025-01-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_management",
            "0006_alter_item_product_alter_item_total_purchase_price_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="quantity_brutto",
            new_name="quantity_gross",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="quantity_netto",
            new_name="quantity_net",
        ),
    ]
