# Generated by Django 4.2.16 on 2025-01-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_management",
            "0007_rename_quantity_brutto_item_quantity_gross_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MainProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Projektentwicklung", "Projektentwicklung"),
                            ("Basisinstallation", "Basisinstallation"),
                            ("Leitungsinfrastruktur", "Leitungsinfrastruktur"),
                            ("IT-Infrastruktur", "IT-Infrastruktur"),
                            ("Ladestation", "Ladestation"),
                        ],
                        default="Projektentwicklung",
                        max_length=128,
                    ),
                ),
                ("group_id", models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="group_name",
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="position_number",
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="project_calculation",
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="total_purchase_price",
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="total_selling_price_margin",
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="productgroup",
            name="item_group",
        ),
        migrations.AddField(
            model_name="itemgroup",
            name="product_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_management.productgroup",
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="group_id",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="MainItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_purchase_price", models.FloatField(null=True)),
                ("total_selling_price_margin", models.FloatField(null=True)),
                (
                    "main_product_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_management.mainproductgroup",
                    ),
                ),
                (
                    "project_calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_management.projectcalculation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="itemgroup",
            name="main_item_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.mainitemgroup",
            ),
        ),
    ]
