# Generated by Django 4.2.16 on 2025-01-19 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_management",
            "0008_mainproductgroup_remove_itemgroup_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productgroup",
            name="main_product_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_management.mainproductgroup",
            ),
        ),
        migrations.AlterField(
            model_name="projectcalculation",
            name="execution_date",
            field=models.DateField(default=datetime.date(2025, 1, 19)),
        ),
    ]
