# Generated by Django 4.2.16 on 2025-01-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0009_productgroup_main_product_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.itemgroup",
            ),
        ),
    ]
